apiVersion: apps/v1
kind: Deployment
metadata:
    name:  nodejs-deployment
    labels:
      app: nodejs-deployment
spec:
 replicas: 1
 selector:
     matchLabels:
      app: nodejs-deployment
 template:
     metadata:
        labels:
            app: nodejs-deployment
     spec:
       containers:
         - name: nodejs-deployment
           image: nginx:latest
           imagePullPolicy: "Always"
           ports:
           - containerPort: 3000